### ISSUE TITLE
Project Idea - Home Depot

### ISSUE THREAD

**Issue by jjohnson2023** [CHS-WBL-2023/Alpha-Secret-Agents#1]
-Create a new website for home depot
-Get rich quick scheme
-Public transport

**Comment by Scoughlin23** [comment]
I feel like the idea could work but we need to figure out what is going to be on the new website.

**Comment by DC0817** [comment]
I think this is a good idea and I agree with @Scoughlin23 their website is in need of a redesign.

**Comment by XCraftMan52** [comment]
In my opinion, This would be hard to accomplish because there is a lot of data involved with their production sites.

**Comment by coliveira14** [comment]
In my opinion I think this is a good idea and agree with @DC0817 their website is in need of a redesign.

**Comment by Scoughlin23** [comment]
hard to design in good sites
