### ISSUE TITLE
Project Idea: Multi-Game Sports Streamer

### ISSUE THREAD

**Issue by DC0817** [CHS-WBL-2023/Alpha-Secret-Agents#5]
Once signed in to the users TV provider, the user can watch all of their favorite sports teams all on one screen, simultaneously. This can save them from switching through multiple tabs, or having to use multiple screens.

**Comment by DC0817** [comment]
This does not just have to be for sports games. It can be other apps such as Disney+, Hulu, Netflix, or more.

**Comment by Scoughlin23** [comment]
not going to do
